Feature/send component info over grpc
Ecdar-SW5/Reveaal pull request #129
Opened 2022-11-15 13:59 UTC by mksm20

Added Specific Component to Refinement, consistency and determinism failure - expanded simple id. tostring and created a getter function for component_id

2022-11-17 08:56 UTC, S3JER requested changes

2022-11-17 08:56 UTC, S3JER commented on src/TransitionSystems/location_id.rs
> +    pub fn get_component_id(&self) -> Option<String> {
Mangler dokumentation ;)

2022-11-17 09:44 UTC, mksm20 commented on src/TransitionSystems/location_id.rs
> +    pub fn get_component_id(&self) -> Option<String> {
er tilføjet

2022-11-17 11:25 UTC, WassawRoki approved these changes
I mean looks fine, men hvad sker der for github actions?

2022-11-17 12:04 UTC, S3JER commented
I skal lige update jeres branch fra main igen, ellers ser det fint ud

2022-11-21 11:04 UTC, S3JER approved these changes

2022-11-21 11:04 UTC, merged