Comminucate cause of failure
Ecdar-SW5/Reveaal pull request #82
Opened 2022-10-27 11:19 UTC by Sigurd00

### Solves #13, #30, #31, #32
### Implemented result enumerations for Refinement, Consistency, and Determinism.

Here is a minimal example of how the response looks for the gui:
![image](https://user-images.githubusercontent.com/24461644/198270057-cd9cb07e-c889-4ca6-bf4e-04d259b609d4.png)

2022-10-27 13:28 UTC, lass5588 commented on src/System/local_consistency.rs
> +                match is_deterministic_helper(new_state, passed_list, system) {
er det ikke redundant med en match hvis vi kun gør noget på false?

2022-10-27 13:34 UTC, lass5588 commented on src/System/local_consistency.rs
> +                match consistency_least_helper(new_state, passed_list, system) {
undgå match her.

2022-10-27 13:38 UTC, lass5588 commented on src/System/local_consistency.rs
> +    //TODO - Why you no work
fjern

2022-10-27 13:38 UTC, lass5588 commented on src/System/local_consistency.rs
> +                match consistency_fully_helper(new_state, passed_list, system) {
unødvendig match

2022-10-27 13:39 UTC, lass5588 commented on src/System/local_consistency.rs
> +                match consistency_fully_helper(new_state, passed_list, system) {
unødvendig match

2022-10-27 13:44 UTC, VictorDore commented on src/System/local_consistency.rs
> +                match is_deterministic_helper(new_state, passed_list, system) {
jeg føler at det er lidt et fedt om man bruger match eller if let

2022-10-27 19:40 UTC, lass5588 commented on src/TransitionSystems/compiled_component.rs
> +//use crate::ProtobufServer::services::query_response::DeterminismResult;
Kan denne linje ikke slettes?

2022-10-27 19:44 UTC, lass5588 commented on src/TransitionSystems/quotient.rs
> +        match S.precheck_sys_rep() {
kan det ikke bare bruge if let her?

2022-11-01 12:23 UTC, S3JER requested changes
Generelt mangler der dokumentation.
Tjek lige jeres todos i koden, om det er noget i kan fikse, ellers spørg @t-lohse omkring hans holdning til dem.

2022-11-01 12:23 UTC, S3JER commented on src/System/local_consistency.rs
> +pub enum ConsistencyFailure {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/local_consistency.rs
> +pub enum DeterminismResult {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/local_consistency.rs
> +pub fn is_deterministic(system: &dyn TransitionSystem) -> DeterminismResult {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/local_consistency.rs
> +pub fn is_fully_consistent(system: &dyn TransitionSystem) -> ConsistencyResult {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/local_consistency.rs
> +                if let ConsistencyResult::Failure(failure) =
Clippy warning!

2022-11-01 12:23 UTC, S3JER commented on src/System/refine.rs
> +pub enum RefinementResult {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/refine.rs
> +pub enum RefinementFailure {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/refine.rs
> +pub enum StatePairResult {
Dokumentation mangler!

2022-11-01 12:23 UTC, S3JER commented on src/System/refine.rs
> +pub fn check_refinement(sys1: TransitionSystemPtr, sys2: TransitionSystemPtr) -> RefinementResult {
Dokumentation mangler!

2022-11-01 13:27 UTC, S3JER submitted a review, later dismissed
LGTM

2022-11-01 13:35 UTC, Sigurd00 commented on src/ProtobufServer/ecdar_requests/send_query.rs
> +                    //TODO: I dont know how to get this info :)
Vi har lavet det her todo til issue #93

2022-11-01 13:45 UTC, S3JER approved these changes

2022-11-02 10:36 UTC, CasperStaahl approved these changes
lgtm

2022-11-02 10:41 UTC, Mightyhaha approved these changes
L G T M

2022-11-02 11:27 UTC, merged