Only do profiling on linux
Ecdar-SW5/Reveaal pull request #95
Opened 2022-11-04 09:36 UTC by mads256h

2022-11-04 12:53 UTC, t-lohse submitted a review, later dismissed

2022-11-04 13:27 UTC, henneboy approved these changes
Looks good to me, had my eyes closed though

2022-11-04 13:29 UTC, henneboy requested changes
Opened my eyes

2022-11-04 13:29 UTC, henneboy commented on benches/flamegraph/flamegraph_profiler.rs
> +        // Not implemented
use unimplemented macro

2022-11-04 13:29 UTC, henneboy commented on benches/flamegraph/flamegraph_profiler.rs
> +        // Not implemented
use unimplemented macro

2022-11-07 10:06 UTC, mads256h commented on benches/flamegraph/flamegraph_profiler.rs
> +        // Not implemented
fixed

2022-11-07 10:06 UTC, mads256h commented on benches/flamegraph/flamegraph_profiler.rs
> +        // Not implemented
fixed

2022-11-07 11:12 UTC, henneboy approved these changes

2022-11-07 11:27 UTC, HTHNLNDN reviewed
Very nice

2022-11-07 11:48 UTC, merged